[tool.poetry]
name = "orcid-link"
version = "0.1.0"
description = ""
authors = ["Erik Pearson <eapearson@lbl.gov>"]

[tool.poetry.dependencies]
python = "3.11.0"
dicttoxml2 = "2.1.0"
fastapi = "0.87.0"
uvicorn = "0.19.0"
requests = "2.28.1"
xmltodict = "0.13.0"
pymongo = "4.3.3"
PyYAML = "6.0"


[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
black = {version = "^22.10.0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
