[tool.poetry]
name = "orcid-link"
version = "0.1.0"
description = ""
authors = ["Erik Pearson <eapearson@lbl.gov>"]

[tool.poetry.dependencies]
python = "3.10.4"
fastapi = "0.79.0"
uvicorn = "0.18.2"
requests = "2.28.1"
xmltodict = "0.13.0"
pymongo = "4.2.0"
PyYAML = "6.0"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
